mqtt:
  host: mosquitto
  port: 1883
  user: asistente
  password: "{FRIGATE_RTSP_PASSWORD}"
  topic_prefix: frigate

detectors:
  cpu1:
    type: cpu
    num_threads: 3

record:
  enabled: true
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10
  motion:
    days: 3

snapshots:
  enabled: true
  retain:
    default: 10

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.7

cameras:
  webcam:
    ffmpeg:
      input_args: -f v4l2 -input_format mjpeg -video_size 1280x720 -framerate 5
      inputs:
        - path: /dev/video0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5

version: 0.17-0
